### PR TITLE
Add support for flake8 analysis

### PR DESCRIPTION
**Pull request by athos-ribeiro**
Signed-off-by: Lucas Kanashiro kanashiro.duarte@gmail.com

### CODE REVIEW

**Comment by sylvestre** [comment]
I think it should be also listed in the slave requirements file.

**Comment by athos-ribeiro** [comment]
It is in the .travis file already. The other analyzers are not listed there in the slave requirements file. What would be the reason to list it there (currently, the only travis and tanglu use the file)?

**Comment by sylvestre** [comment]
Because the other analyzers are not available in pip ;)

**Comment by sylvestre** [comment]
ping?

**Comment by sylvestre** [comment]
(and the patch must be rebased)

**Comment by athos-ribeiro** [comment]
Done!

**Comment by sylvestre** [comment]
Thanks :)

**Pull request merged**
