### PR TITLE
Ruby static analyzer

### PR DESCRIPTION
**Pull request by lukhio**
This static analyzer uses roodi (https://tracker.debian.org/pkg/roodi) to parse ruby code.

### CODE REVIEW

**Comment by sylvestre** [comment]
Please rebase all patches in a single commit.

**Comment by clemux** [comment]
flake8 tests don't pass: 
https://travis-ci.org/opencollab/debile/builds/55626572

**Comment by clemux** [comment]
> the package is probably missing.

Indeed. Julien: you should add a test that checks that roodi is
installed. 

Or maybe patch roodi to add a CLI argument that prints roodi's version,
and then implement test_version() as for the other debile check.

**Comment by sylvestre** [comment]
In this case, I would prefer to have the package installed in https://github.com/opencollab/debile/blob/master/.travis.yml

**Comment by lukhio** [comment]
@sylvestre ok I'm on it.

@clemux ok, I'll add the test too. I'll look into patching roodi right after that.

**Comment by clemux** [comment]
> @sylvestre ok I'm on it.
> 
> @clemux ok, I'll add the test too. I'll look into patching roodi right after that.

Also your commit contains the diff from commit 6632966. This should not
have happened, and you probably did the rebase wrong.

**Comment by lukhio** [comment]
@sylvestre I removed the line. Is there any other problems ?

About the test to check if roodi is installed, should I just check for roodi to be there or should I patch roodi and implement a test_version() function ?

**Comment by sylvestre** [comment]
Excellent, good work. Thanks.

In a separate PR, could you also update debian/control to add the roodi dependency?

**Comment by lukhio** [comment]
Yep, right away.

**Pull request merged**
