### PR TITLE
Solution for some issues in docker config

### PR DESCRIPTION
**Pull request by Mohit7**

### CODE REVIEW

**Comment by sylvestre** [comment]
It seems that there are patches unrelated to docker, correct? If it is the case, could you separate them into different PR ? thanks

**Comment by sylvestre** [comment]
ping ?

**Comment by Mohit7** [comment]
Hey, sorry missed Aug 13 mail, I will do that and submit it.

**Comment by sylvestre** [comment]
@Mohit7 ping ? :)

**Comment by Mohit7** [comment]
Hey, sorry again, will do it soon.

**Comment by sylvestre** [comment]
ping ?

**Comment by clemux** [comment]
This looks fine to me. Can you open an issue for [https://github.com/opencollab/debile/pull/37/commits/a81898c32b7dabbc520510eb4525733fb4ffdb2f]?

**Comment by clemux** [comment]
Closes #12.

**Pull request merged**
