### PR TITLE
Add the support for pylint

### PR DESCRIPTION
**Pull request by lucaskanashiro**
Signed-off-by: Athos Ribeiro athoscribeiro@gmail.com

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
Perhaps, but pylint is not a requeriment of any slave, is it? This requeriments-slave.txt set environment for any slave?

**Comment by sylvestre** [comment]
All slaves will have all checkers. So, it doesn't matter much

**Comment by lucaskanashiro** [comment]
Done.

**Comment by sylvestre** [comment]
Do you agree with the change or you did that to make me happy ? :)

**Comment by sylvestre** [comment]
And I am pretty sure it can be removed from .travis now.

**Comment by lucaskanashiro** [comment]
I agree, because if all slaves run all the checkers it's all right.

**Comment by sylvestre** [comment]
could you remove it from .travis?

**Comment by lucaskanashiro** [comment]
It was already removed, I reseted the previous commit :-)

**Comment by sylvestre** [comment]
sorry, my bad :)

**Pull request merged**
